//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xecrets.Texts.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InvariantResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvariantResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xecrets.Texts.Properties.InvariantResources", typeof(InvariantResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DisplayNameCliTools {
            get {
                return ResourceManager.GetString("DisplayNameCliTools", resourceCulture);
            }
        }
        
        internal static string DisplayNameProgram {
            get {
                return ResourceManager.GetString("DisplayNameProgram", resourceCulture);
            }
        }
        
        internal static string DisplayNameSdkApi {
            get {
                return ResourceManager.GetString("DisplayNameSdkApi", resourceCulture);
            }
        }
        
        internal static string EzFeaturesUrl {
            get {
                return ResourceManager.GetString("EzFeaturesUrl", resourceCulture);
            }
        }
        
        internal static string FileEncryptionUrl {
            get {
                return ResourceManager.GetString("FileEncryptionUrl", resourceCulture);
            }
        }
        
        internal static string GetLicenseUrlFormat {
            get {
                return ResourceManager.GetString("GetLicenseUrlFormat", resourceCulture);
            }
        }
        
        internal static string GetTrialUrlFormat {
            get {
                return ResourceManager.GetString("GetTrialUrlFormat", resourceCulture);
            }
        }
        
        internal static string GetXecretsUrl {
            get {
                return ResourceManager.GetString("GetXecretsUrl", resourceCulture);
            }
        }
        
        internal static string MenuEnglish {
            get {
                return ResourceManager.GetString("MenuEnglish", resourceCulture);
            }
        }
        
        internal static string MenuFrench {
            get {
                return ResourceManager.GetString("MenuFrench", resourceCulture);
            }
        }
        
        internal static string MenuGerman {
            get {
                return ResourceManager.GetString("MenuGerman", resourceCulture);
            }
        }
        
        internal static string MenuItalian {
            get {
                return ResourceManager.GetString("MenuItalian", resourceCulture);
            }
        }
        
        internal static string MenuPortugueseBrasil {
            get {
                return ResourceManager.GetString("MenuPortugueseBrasil", resourceCulture);
            }
        }
        
        internal static string MenuSpanish {
            get {
                return ResourceManager.GetString("MenuSpanish", resourceCulture);
            }
        }
        
        internal static string MenuSwedish {
            get {
                return ResourceManager.GetString("MenuSwedish", resourceCulture);
            }
        }
        
        internal static string UrlDownloadXecretsFormat {
            get {
                return ResourceManager.GetString("UrlDownloadXecretsFormat", resourceCulture);
            }
        }
        
        internal static string XecretsHelpUrl {
            get {
                return ResourceManager.GetString("XecretsHelpUrl", resourceCulture);
            }
        }
        
        internal static string PasswordResetId {
            get {
                return ResourceManager.GetString("PasswordResetId", resourceCulture);
            }
        }
        
        internal static string LicenseHelpId {
            get {
                return ResourceManager.GetString("LicenseHelpId", resourceCulture);
            }
        }
        
        internal static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        internal static string TurnDebugOff {
            get {
                return ResourceManager.GetString("TurnDebugOff", resourceCulture);
            }
        }
        
        internal static string TurnDebugOn {
            get {
                return ResourceManager.GetString("TurnDebugOn", resourceCulture);
            }
        }
        
        internal static string CustomerPortalUrl {
            get {
                return ResourceManager.GetString("CustomerPortalUrl", resourceCulture);
            }
        }
        
        internal static string YouTubeVideosUrl {
            get {
                return ResourceManager.GetString("YouTubeVideosUrl", resourceCulture);
            }
        }
        
        internal static string ShamirsSecretSharing {
            get {
                return ResourceManager.GetString("ShamirsSecretSharing", resourceCulture);
            }
        }
        
        internal static string ReleaseNotesUrl {
            get {
                return ResourceManager.GetString("ReleaseNotesUrl", resourceCulture);
            }
        }
        
        internal static string RequestReviewUrl {
            get {
                return ResourceManager.GetString("RequestReviewUrl", resourceCulture);
            }
        }
        
        internal static string CliVersionMismatchHelpId {
            get {
                return ResourceManager.GetString("CliVersionMismatchHelpId", resourceCulture);
            }
        }
        
        internal static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        internal static string MenuPolish {
            get {
                return ResourceManager.GetString("MenuPolish", resourceCulture);
            }
        }
    }
}
